### PR TITLE
Render helper with block containing Arbre element.

### LINKED ISSUE #46: using link_to with block in arbre template
index.html.arb with such code

``` ruby
h1 'Dashboard#index'
para 'Find me in app/views/dashboard/index.html.arb'
link_to sign_out_path, data: {confirm: 'Are you sure?'}, method: :delete do
  i 'Logout', class: 'fa fa-lock'
end
```

generate incorrect html

``` html
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.arb</p>
<i class="fa fa-lock">Logout</i>
```

i can use text_node only if i use `link_to` without block

``` ruby
text_node link_to('Logout', sign_out_path, method: :delete).html_safe
```

``` html
<a rel="nofollow" data-method="delete" href="/sign_out">Logout</a>
```

i think same situation will be with any helper method with block that returns html

### PR DESCRIPTION
**Pull request by varyonic**
This PR fixes #46 following the first option suggested by Sean.  It monkey-patches ActionView::Base#capture so that the output of Arbre elements is not lost inside a Rails helper block, and it modifies Arbre::Element#method_missing to capture the output of Rails helper calls into text_nodes.

### CODE REVIEW

**Comment by Fivell** [comment]
@varyonic , is it still WIP ?

**Comment by varyonic** [comment]
I marked this as [WIP] because even though the tests pass it breaks ActiveAdmin in various ways.  I've shelved this until I (or someone else) cleans up ActiveAdmin (only call a helper through method_missing if any string returned should be rendered).

File: lib/arbre/rails/template_handler.rb [hunk 1]
```diff
@@ -1,3 +1,19 @@
+ActionView::Base.class_eval do
+  def capture(*args)
+    value = nil
+    buffer = with_output_buffer { value = yield(*args) }
+
+    # Override to handle Arbre elements inside helper blocks.
+    # See https://github.com/rails/rails/issues/17661
+    # and https://github.com/rails/rails/pull/18024#commitcomment-8975180
+    value = value.to_s if value.is_a?(Arbre::Element)
```
Comment (varyonic) [inline lib/arbre/rails/template_handler.rb]: Copied ActionView::Helpers::CaptureHelper.capture and added this line to convert Arbre::Element#to_s so the output is not lost.

**Comment by varyonic** [comment]
I was overcomplicating things by trying to eliminate text_node.  link_to works with text_node and now the arbre inside the link_to block is captured and displayed in the order expected.

File: lib/arbre/rails/template_handler.rb [hunk 2]
```diff
@@ -1,3 +1,21 @@
+# frozen_string_literal: true
+
+ActionView::Base.class_eval do
```
Comment (seanlinsley) [inline lib/arbre/rails/template_handler.rb]: Perhaps this should be moved to its own file, named something like `lib/arbre/rails/capture.rb`

**Comment by seanlinsley** [comment]
One concern with the monkeypatch is that it doesn't call the original implementation, so another gem that overrode `capture` would be in contention with Arbre.

This might work as an alternative:

```ruby
ActionView::Base.prepend Module.new {
  def capture(*args)
    super *args do
      value = yield *args
      value = value.to_s if value.is_a? Arbre::Element
      value
    end
  end
}
```
I'm not sure if `with_output_buffer` is needed; since this basically just wraps the block in another block, the original implementation's call to `with_output_buffer` should theoretically be enough.

**Comment by varyonic** [comment]
I'm going to take this as approved and consider the suggestions for later.
